import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MobileFrame from "@/components/MobileFrame.jsx";
import WebFrame from "@/components/WebFrame.jsx";
import GlobalAudio from "@/components/GlobalAudio";
import SmokeEffect from "@/components/SmokeEffect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalAudio />
        <MobileFrame />
        <SmokeEffect />
        {/* <WebFrame /> */}
        {children}
      </body>
    </html>
  );
}
